### ISSUE TITLE
[Ryan] Ride the Windy Windmill

### ISSUE THREAD

**Issue by nayrpg** [MadeMadeDane/castle_o_puzzles#127]
I want to be able to glide from a high windmill to a lower platform to reach my first moon.

My implementation include two platforms and a gliding block. The player higher windmill platform down to the lower platform to get the moon.

**Comment by Feesh7** [comment]
:-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:
