### ISSUE TITLE
Add support for "use items" (name pending)

### ISSUE THREAD

**Issue by Feesh7** [MadeMadeDane/castle_o_puzzles#95]
We need proper support for what we've been calling "use items" up until now. The terminology here is confusing because we have an entirely separate "use button" so we should also use this issue to resolve the naming conflicts.

Use items are items that only exist in the current map and are shared among all players. These items have simple controls (a single button on the controller) however they will be context dependent and will provide diverse uses. They will also be able to be combined with one another to form another use item. Examples of use items would be keys, rope, chemicals, a light bulb, etc...

**Comment by nayrpg** [comment]
We should diagram this. @Feesh7 You got time for this sometime soon?

**Comment by nayrpg** [comment]
From this moment forward "Use Items" will be referred to Shared Items.
